### ISSUE TITLE
Help is not printed: There are 9 help pages that matches the given result

### ISSUE THREAD

**Issue by crtl** [fastify/fastify-cli#388] opened 2021-06-16 12:40 UTC
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x.x

### Node.js version

14.17.0

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

10

### Description

Ive installed fastify on `windows 10` over `git bash` using `yarn`.
When typing `fastify` command the following is printed:
```
There are 9 help pages that matches the given request, please disambiguate:
  * C:/Users/User/AppData/Roaming/npm/node_modules/fastify-cli/help/docs
  * C:/Users/User/AppData/Roaming/npm/node_modules/fastify-cli/help/eject-ts
  * C:/Users/User/AppData/Roaming/npm/node_modules/fastify-cli/help/eject
  * C:/Users/User/AppData/Roaming/npm/node_modules/fastify-cli/help/generate-plugin
  * C:/Users/User/AppData/Roaming/npm/node_modules/fastify-cli/help/generate
  * C:/Users/User/AppData/Roaming/npm/node_modules/fastify-cli/help/help
  * C:/Users/User/AppData/Roaming/npm/node_modules/fastify-cli/help/print-routes
  * C:/Users/User/AppData/Roaming/npm/node_modules/fastify-cli/help/readme
  * C:/Users/User/AppData/Roaming/npm/node_modules/fastify-cli/help/start
```

Ive tried removing it with `yarn` and install with `npm` which produces the same result.
Running in Windows CMD produces the same result.

### Steps to Reproduce

```
yarn global install fastify-cli
fastify
```

### Expected Behavior

The help page should be printed like shown in the docs.

**EDIT**:
`fastify help` produces the same output.

**Comment by mcollina** [comment] 2021-06-17 14:19
Would you like to send a PR to fix this? It looks like this a Windows bug somewhere and I do not have a Windows machine handy. 
Would you like to send a Pull Request to address this issue? Remember to add unit tests.

**Comment by khattakdev** [comment] 2021-06-18 08:42
This seems to be an issue with either `glob` ([npm package](https://www.npmjs.com/package/glob)) or `help-me` ([npm package](https://www.npmjs.com/package/help-me))

Here's how you can reproduce it.

Executing the following code:
```
const glob = require("glob");

const opts = {
  ext: ".txt",
  help: "help",
  dir: "d:\\work\\fastify-cli\\help",
};

glob(opts.dir + "/**/*" + opts.ext, (err, files) => {
  if (err) console.log(err);
  console.log(files);
});
```

`help-me` has some similar code (the first argument passed to `glob`).

**Comment by mcollina** [comment] 2021-06-18 08:45
I'm not sure how would you fix it.

**Comment by khattakdev** [comment] 2021-06-18 08:50
I'll try to find a fix for this. I'm not familiar with `help-me` or `glob` so need to experience with `glob` a little bit. I think it has something to do with the first argument we pass to `glob`. I tried `path.join` as well as `path.resolve` but couldn't find a fix yet.
Will look into it.

**Comment by khattakdev** [comment] 2021-06-18 11:38
@mcollina After debugging for a while, I found out that this is an issue on `help-me` package. I found a fix for this as well, will create a Pull Request on `help-me` repo.

**Comment by mcollina** [comment] 2021-06-18 11:41
Thanks!!

**Closed** 2021-06-22 13:00 UTC
Labels: bug, good first issue
