### ISSUE TITLE
Some files not shows on coverage

### ISSUE THREAD

**Issue by RafaelGSS** [fastify/fastify-cli#274] opened 2020-09-26 14:21 UTC
## 🐛 Bug Report

Based on #269. We discovered that some files (with tests) are not shown on tap coverage, and it's bad because we can forgot to test some branches.

## To Reproduce

```sh
npx tap --coverage test/generate.test.js
```

## Expected behavior

Show a list of coverage on this test. Instead, it shows empty tests like on the image bellow
![image](https://user-images.githubusercontent.com/26234614/94342822-210aaf80-ffea-11ea-8baf-1b9e91add5cd.png)

_Obs: New files are following this behavior see [here](https://github.com/fastify/fastify-cli/pull/269#issuecomment-699133991)_

## Your Environment

- *node version*: 12
- *fastify version*: >=3.0.0
- *os*: Linux

**Comment by mcollina** [comment] 2020-09-26 22:47
I literally have no clue about this.

**Comment by Eomm** [comment] 2020-09-27 11:05
The issue here is caused by https://github.com/istanbuljs/nyc/issues/1287

I spotted this issue some weeks ago and for this reason/frustration, I asked ["why?"](https://stackoverflow.com/questions/63850046/why-prefer-es6-import-over-require).

**Comment by mcollina** [comment] 2020-09-27 15:30
Closing as wontfix as there is no possible path of fixing this in this module.

**Closed by mcollina** 2020-09-27 15:30 UTC
Labels: dependencies, wontfix

**Comment by alemagio** [comment] 2020-09-27 16:09
As a momentary fix I found out that launching `nyc tap ...` shows the correct coverage table:

![master_nyc](https://user-images.githubusercontent.com/21338507/94369865-8e066e00-00ec-11eb-8af2-78ae2bd718bf.png)
